# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\57799\Downloads\chatroom-master\chatroom-master\Serverui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userTable = QtWidgets.QTableWidget(self.centralwidget)
        self.userTable.setRowCount(0)
        self.userTable.setColumnCount(3)
        self.userTable.setObjectName("userTable")
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.userTable)
        self.startServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.startServerButton.setObjectName("startServerButton")
        self.verticalLayout.addWidget(self.startServerButton)
        self.stopServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopServerButton.setObjectName("stopServerButton")
        self.verticalLayout.addWidget(self.stopServerButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Server Manager"))
        item = self.userTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.userTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kick"))
        item = self.userTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ban"))
        self.startServerButton.setText(_translate("MainWindow", "Start Server"))
        self.stopServerButton.setText(_translate("MainWindow", "Stop Server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
