# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\57799\Desktop\Semestre3\SAE302\SAE302_Yulei\Serverui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logArea = QtWidgets.QTextEdit(self.centralwidget)
        self.logArea.setReadOnly(True)
        self.logArea.setObjectName("logArea")
        self.verticalLayout.addWidget(self.logArea)
        self.userTable = QtWidgets.QTableWidget(self.centralwidget)
        self.userTable.setRowCount(0)
        self.userTable.setColumnCount(4)
        self.userTable.setObjectName("userTable")
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.userTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.startServerButton.setObjectName("startServerButton")
        self.horizontalLayout.addWidget(self.startServerButton)
        self.stopServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopServerButton.setObjectName("stopServerButton")
        self.horizontalLayout.addWidget(self.stopServerButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.commandLayout = QtWidgets.QHBoxLayout()
        self.commandLayout.setObjectName("commandLayout")
        self.commandInput = QtWidgets.QLineEdit(self.centralwidget)
        self.commandInput.setObjectName("commandInput")
        self.commandLayout.addWidget(self.commandInput)
        self.executeCommandButton = QtWidgets.QPushButton(self.centralwidget)
        self.executeCommandButton.setObjectName("executeCommandButton")
        self.commandLayout.addWidget(self.executeCommandButton)
        self.verticalLayout.addLayout(self.commandLayout)
        self.channelRequestGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.channelRequestGroupBox.setObjectName("channelRequestGroupBox")
        self.channelRequestLayout = QtWidgets.QVBoxLayout(self.channelRequestGroupBox)
        self.channelRequestLayout.setObjectName("channelRequestLayout")
        self.comptabiliteRequestWidget = QtWidgets.QWidget(self.channelRequestGroupBox)
        self.comptabiliteRequestWidget.setObjectName("comptabiliteRequestWidget")
        self.comptabiliteRequestLayout = QtWidgets.QHBoxLayout(self.comptabiliteRequestWidget)
        self.comptabiliteRequestLayout.setObjectName("comptabiliteRequestLayout")
        self.comptabiliteLabel = QtWidgets.QLabel(self.comptabiliteRequestWidget)
        self.comptabiliteLabel.setObjectName("comptabiliteLabel")
        self.comptabiliteRequestLayout.addWidget(self.comptabiliteLabel)
        self.comptabiliteUserInput = QtWidgets.QLineEdit(self.comptabiliteRequestWidget)
        self.comptabiliteUserInput.setObjectName("comptabiliteUserInput")
        self.comptabiliteRequestLayout.addWidget(self.comptabiliteUserInput)
        self.comptabiliteApproveButton = QtWidgets.QPushButton(self.comptabiliteRequestWidget)
        self.comptabiliteApproveButton.setObjectName("comptabiliteApproveButton")
        self.comptabiliteRequestLayout.addWidget(self.comptabiliteApproveButton)
        self.comptabiliteDenyButton = QtWidgets.QPushButton(self.comptabiliteRequestWidget)
        self.comptabiliteDenyButton.setObjectName("comptabiliteDenyButton")
        self.comptabiliteRequestLayout.addWidget(self.comptabiliteDenyButton)
        self.channelRequestLayout.addWidget(self.comptabiliteRequestWidget)
        self.verticalLayout.addWidget(self.channelRequestGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Server Manager"))
        item = self.userTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.userTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.userTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port"))
        item = self.userTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actions"))
        self.startServerButton.setText(_translate("MainWindow", "Start Server"))
        self.stopServerButton.setText(_translate("MainWindow", "Stop Server"))
        self.commandInput.setPlaceholderText(_translate("MainWindow", "Enter admin command"))
        self.executeCommandButton.setText(_translate("MainWindow", "Execute Command"))
        self.channelRequestGroupBox.setTitle(_translate("MainWindow", "Channel Requests"))
        self.comptabiliteLabel.setText(_translate("MainWindow", "Comptabilité:"))
        self.comptabiliteUserInput.setPlaceholderText(_translate("MainWindow", "User Request"))
        self.comptabiliteApproveButton.setText(_translate("MainWindow", "Approve"))
        self.comptabiliteDenyButton.setText(_translate("MainWindow", "Deny"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
